### ISSUE TITLE
KGE Fails when the patient id's are numbers

### ISSUE THREAD

**Issue by vinaysb** [hybrid-kg/clep#22]
When KGE is executed on data where the patient ids are numbers, the pandas dataframe interprets the number as integers instead of string

**Comment by cthoyt** [comment]
Always pass dtype=str when doing read_csv

**Comment by vinaysb** [comment]
That was what I was thinking to do, but the data is floating-point, so I am thinking of just typecasting the index to str in the code

**Comment by cthoyt** [comment]
Okay, then it's possible to give a dictionary to dtype mapping from the column name to the type. Anything you don't make explicit is automatically inferred. 

Otherwise your solution is fine (basically the same). Just be careful in case it's possible there are ever null values since those can get cast to strings as well

**Comment by vinaysb** [comment]
Fixed in aee06faa88f8f26abd9a752ac14339c0378cb9de
